project_root/apps/a0_foundation/urls.py
from django_distill import distill_path

# from .views import StatusView

from django.views.generic import TemplateView


def get_status():
    return None


urlpatterns = [

    # note: GitLab Pages works without the trailing slash,
    # but GitHub Pages does not
    distill_path('status/',
                 TemplateView.as_view(
                    template_name='foundation/status.html'
                 ),
                 name='status',
                 distill_func=get_status),

]

project_root/apps/blog/urls.py
from django_distill import distill_path

from .views import IndexView, PostView, TagView
from .models import Post, Tag

from django.views.generic import TemplateView


def get_index():
    return None


def get_posts():
    for post in Post.objects.published():
        yield {'slug': post.slug}


def get_tags():
    for tag in Tag.objects.all():
        yield {'tag': tag.name}


urlpatterns = [

    # should be blog/ if a blog is not the home page
    distill_path('',
                 IndexView.as_view(),
                 name='blog-index',
                 distill_func=get_index,
                 distill_file='index.html'),

    distill_path('blog/post/<slug:slug>.html',
                 PostView.as_view(),
                 name='blog-post',
                 distill_func=get_posts),

    distill_path('blog/tag/<slug:tag>.html',
                 TagView.as_view(),
                 name='blog-tag',
                 distill_func=get_tags),

]

project_root/apps/blog_original_snapshot/urls.py
from django_distill import distill_path
from .views import IndexView, PostView, TagView
from .models import Post, Tag


def get_index():
    return None


def get_posts():
    for post in Post.objects.published():
        yield {'slug': post.slug}


def get_tags():
    for tag in Tag.objects.all():
        yield {'tag': tag.name}


urlpatterns = [

    distill_path('',
                 IndexView.as_view(),
                 name='blog-index',
                 distill_func=get_index,
                 distill_file='index.html'),

    distill_path('post/<slug:slug>.html',
                 PostView.as_view(),
                 name='blog-post',
                 distill_func=get_posts),

    distill_path('tag/<slug:tag>.html',
                 TagView.as_view(),
                 name='blog-tag',
                 distill_func=get_tags),

]

project_root/apps/a0_foundation/models.py
from django.db import models

# Create your models here.

project_root/apps/blog/models.py
from django.db import models
from django.db.models import Q
from django.contrib.auth import get_user_model
from django.utils import timezone



class PostManager(models.Manager):

    def published(self):
        now = timezone.now()
        return self.filter(Q(publish_date__lte=now)|Q(publish_date=None))


class Tag(models.Model):

    name = models.SlugField(
        max_length=32,
        db_index=True,
        unique=True,
        help_text='Tag name'
    )

    def __str__(self):
        return self.name


class Post(models.Model):

    objects = PostManager()

    author = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE,
        help_text='Author of the post'
    )
    created = models.DateTimeField(
        auto_now_add=True,
        help_text='Date and time the post was created'
    )
    updated = models.DateTimeField(
        auto_now=True,
        help_text='Date and time the post was last updated',
    )
    publish_date = models.DateTimeField(
        blank=True,
        null=True,
        help_text='(optional) If set, when to publish the post'
    )
    title = models.CharField(
        max_length=255,
        help_text='Title of the post'
    )
    slug = models.SlugField(
        help_text='Slug of the post',
        db_index=True,
        unique=True,
        null=True,
        blank=True,
    )
    content = models.TextField(
        help_text='Content of the post'
    )
    tags = models.ManyToManyField(
        Tag,
        help_text='Tags'
    )

    def __str__(self):
        return self.title

project_root/apps/blog_original_snapshot/models.py
from django.db import models
from django.db.models import Q
from django.contrib.auth import get_user_model
from django.utils import timezone



class PostManager(models.Manager):

    def published(self):
        now = timezone.now()
        return self.filter(Q(publish_date__lte=now)|Q(publish_date=None))


class Tag(models.Model):

    name = models.SlugField(
        max_length=32,
        db_index=True,
        unique=True,
        help_text='Tag name'
    )

    def __str__(self):
        return self.name


class Post(models.Model):

    objects = PostManager()

    author = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE,
        help_text='Author of the post'
    )
    created = models.DateTimeField(
        auto_now_add=True,
        help_text='Date and time the post was created'
    )
    updated = models.DateTimeField(
        auto_now=True,
        help_text='Date and time the post was last updated',
    )
    publish_date = models.DateTimeField(
        blank=True,
        null=True,
        help_text='(optional) If set, when to publish the post'
    )
    title = models.CharField(
        max_length=255,
        help_text='Title of the post'
    )
    slug = models.SlugField(
        help_text='Slug of the post',
        db_index=True,
        unique=True,
        null=True,
        blank=True,
    )
    content = models.TextField(
        help_text='Content of the post'
    )
    tags = models.ManyToManyField(
        Tag,
        help_text='Tags'
    )

    def __str__(self):
        return self.title

project_root/apps/a0_foundation/views.py
from django.shortcuts import render

# Create your views here.

project_root/apps/blog/views.py
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from .models import Post, Tag


class IndexView(ListView):

    template_name = 'blog/index.html'
    model = Post
    allow_empty = False
    queryset = Post.objects.published()
    ordering = '-created'
    context_object_name = 'posts'


class PostView(DetailView):

    template_name = 'blog/post.html'
    model = Post


class TagView(DetailView):

    template_name = 'blog/tag.html'
    model = Tag
    slug_url_kwarg = 'tag'
    slug_field = 'name'

project_root/apps/blog_original_snapshot/views.py
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from .models import Post, Tag


class IndexView(ListView):

    template_name = 'index.html'
    model = Post
    allow_empty = False
    queryset = Post.objects.published()
    ordering = '-created'
    context_object_name = 'posts'


class PostView(DetailView):

    template_name = 'post.html'
    model = Post


class TagView(DetailView):

    template_name = 'tag.html'
    model = Tag
    slug_url_kwarg = 'tag'
    slug_field = 'name'

project_root/apps/a0_foundation/templates/foundation/base.html
{% load cdnstaticfiles %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}&nbsp;&#183;&nbsp;{{ SITE_TITLE }}{% if SITE_HEAD_TITLE_ENV %}&nbsp;[{{ SITE_HEAD_TITLE_ENV }}]{% endif %}</title>
        <meta name="title" content="{% block title_meta %}{% endblock %}&nbsp;&#183;&nbsp;{{ SITE_TITLE }}">

        <meta name="viewport" content="width=device-width, initial-scale=1">
        
        <link rel="stylesheet" href="{% cdnstatic 'foundation/css/tachyons.min.css' %}'">
        <link rel="stylesheet" href="{% cdnstatic 'foundation/css/blog.css' %}'">
    </head>
    <body>
        {% include 'foundation/inc/header_nav_global.html' %}
        <section class="mw7 center">
            <h1 class="athelas ph3 ph0-l"><a href="{% url 'blog-index' %}">Some Demo Blog</a></a></h1>
            {% block content %}{% endblock %}
        </section>
        <footer class="mw7 center">
            <div class="pv4 bt bb b--black-10 ph3 ph0-l">
                <p>This is a demo site built with <a href="https://github.com/meeb/django-distill">django-distill</a>, a static site generator for Django. Source code is available at <a href="https://github.com/meeb/django-distill-example">django-distill-example</a>. It also uses <a href="https://tachyons.io/">Tachyons</a> for styling. Now works with Django 4!</p>
            </div>
        </footer>
    </body>
</html>

project_root/apps/a0_foundation/templates/foundation/inc/header_nav_global.html
<nav class="pa3 pa4-ns">

    <a class="link dim gray f6 f5-ns dib mr3" href="{% url 'blog-index' %}" title="Blog">Blog</a>

    <a class="link dim gray f6 f5-ns dib mr3" href="{% url 'status' %}" title="Status">Status</a>
    
    {% comment "" %}{% if DEBUG %}{% endcomment %}
    {# note that the Admin app is not distilled #}
    {% if user.is_authenticated %}{% if request.user.is_superuser %}
        <a class="link dim gray f6 f5-ns dib mr3" href="{% url 'admin:index' %}" title="Admin">Admin</a>
    {% endif %}{% endif %} {# end Admin #}
    {% comment "" %}{% endif %} {# end DEBUG #}{% endcomment %}

</nav>

project_root/apps/a0_foundation/templates/foundation/status.html
{% extends 'foundation/base.html' %}

{% block title %}Status{% endblock %}
{% block title_meta %}Status{% endblock %}

{% block content %}
    <p>
        <strong>Site last built:</strong> {{ CURRENT_AWARE_DATETIME }}
    </p>

    <h2>Platform Information</h2>
    
    <ul>
        <li>Python: {{ PYTHON_VERSION }}</li>
        <li>Pip: {{ PIP_VERSION }}</li>
        <li>Django: {{ DJANGO_VERSION }}</li>
        <li>django-distill: {{ DISTILL_VERSION }}</li>
        <li>django-htmlmin {{ HTMLMIN_VERSION }}</li>
        <li>OS: {{ OS_VERSION }}</li>

        {% comment "" %}
        <li> {{  }}</li>
        <li> {{  }}</li>
        {% endcomment %}
    </ul>

    <h2>All Versions Of This Page</h2>

    <ul>
        <li><a href="https://disjecta.github.io/status/">GitHub Pages</a></li>
        <li><a href="https://disjecta.gitlab.io/status/">GitLab Pages</a></li>
        <li><a href="https://disjecta.netlify.app/status/">Netlify</a></li>
    </ul>

{% endblock %}

project_root/apps/blog/templates/blog/_post.html
<article class="pv4 bt bb b--black-10 ph3 ph0-l">
    <div class="flex flex-column flex-row-ns">
        <div class="w-100 pr3-ns order-2 order-1-ns">
            <h1 class="f3 athelas mt0 lh-title"><a href="{% url 'blog-post' slug=post.slug %}">{{ post.title }}</a></h1>
            <p class="f5 f4-l lh-copy athelas">{{ post.content|linebreaks }}</p>
        </div>
    </div>
    <p class="tags">
    {% for tag in post.tags.all %}
        <a class="f6 link dim br1 ph3 pv2 mb2 dib white bg-black" href="{% url 'blog-tag' tag=tag.name %}">{{ tag.name }}</a>
    {% endfor %}
    </p>
    <p class="f6 lh-copy gray mv0">By <span class="ttu">{{ post.author }}</span></p>
    <time class="f6 db gray">{{ post.updated }}</time>
</article>

project_root/apps/blog/templates/blog/index.html
{% extends 'foundation/base.html' %}

{% block title %}All posts{% endblock %}

{% block content %}
    {% for post in posts %}
        {% include 'blog/_post.html' with post=post %}
    {% endfor %}
{% endblock %}

project_root/apps/blog/templates/blog/post.html
{% extends 'foundation/base.html' %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
    {% include 'blog/_post.html' with post=post %}
{% endblock %}

project_root/apps/blog/templates/blog/tag.html
{% extends 'foundation/base.html' %}

{% block title %}Posts matching &quot;{{ tag.name }}&quot;{% endblock %}

{% block content %}
    <div class="pv2 bt bb b--black-10 ph3 ph0-l">
        <h2 class="f3 athelas">Posts tagged with &quot;{{ tag.name }}&quot;</h2>
    </div>
    <div class="pv4">
    {% for post in tag.post_set.published %}
        <p><a href="{% url 'blog-post' slug=post.slug %}">{{ post.title }}</a></p>
    {% endfor %}
    </div>
{% endblock %}

project_root/apps/blog_original_snapshot/templates/_post.html
<article class="pv4 bt bb b--black-10 ph3 ph0-l">
    <div class="flex flex-column flex-row-ns">
        <div class="w-100 pr3-ns order-2 order-1-ns">
            <h1 class="f3 athelas mt0 lh-title"><a href="{% url 'blog-post' slug=post.slug %}">{{ post.title }}</a></h1>
            <p class="f5 f4-l lh-copy athelas">{{ post.content|linebreaks }}</p>
        </div>
    </div>
    <p class="tags">
    {% for tag in post.tags.all %}
        <a class="f6 link dim br1 ph3 pv2 mb2 dib white bg-black" href="{% url 'blog-tag' tag=tag.name %}">{{ tag.name }}</a>
    {% endfor %}
    </p>
    <p class="f6 lh-copy gray mv0">By <span class="ttu">{{ post.author }}</span></p>
    <time class="f6 db gray">{{ post.updated }}</time>
</article>

project_root/apps/blog_original_snapshot/templates/base.html
{% load cdnstaticfiles %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Some Demo Blog - {% block title %}{% endblock %}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{% cdnstatic 'styles/tachyons.min.css' %}'">
        <link rel="stylesheet" href="{% cdnstatic 'styles/blog.css' %}'">
    </head>
    <body>
        <section class="mw7 center">
            <h1 class="athelas ph3 ph0-l"><a href="{% url 'blog-index' %}">Some Demo Blog</a></a></h1>
            {% block content %}{% endblock %}
        </section>
        <footer class="mw7 center">
            <div class="pv4 bt bb b--black-10 ph3 ph0-l">
                <p>This is a demo site built with <a href="https://github.com/meeb/django-distill">django-distill</a>, a static site generator for Django. Source code is available at <a href="https://github.com/meeb/django-distill-example">django-distill-example</a>. It also uses <a href="https://tachyons.io/">Tachyons</a> for styling. Now works with Django 4!</p>
            </div>
        </footer>
    </body>
</html>

project_root/apps/blog_original_snapshot/templates/index.html
{% extends 'base.html' %}

{% block title %}All posts{% endblock %}

{% block content %}
    {% for post in posts %}
        {% include '_post.html' with post=post %}
    {% endfor %}
{% endblock %}

project_root/apps/blog_original_snapshot/templates/post.html
{% extends 'base.html' %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
    {% include '_post.html' with post=post %}
{% endblock %}

project_root/apps/blog_original_snapshot/templates/tag.html
{% extends 'base.html' %}

{% block title %}Posts matching &quot;{{ tag.name }}&quot;{% endblock %}

{% block content %}
    <div class="pv2 bt bb b--black-10 ph3 ph0-l">
        <h2 class="f3 athelas">Posts tagged with &quot;{{ tag.name }}&quot;</h2>
    </div>
    <div class="pv4">
    {% for post in tag.post_set.published %}
        <p><a href="{% url 'blog-post' slug=post.slug %}">{{ post.title }}</a></p>
    {% endfor %}
    </div>
{% endblock %}